/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#pragma once

// CPU golden for aclblasCsyrk (complex64). The reference loop itself lives in
// blas/syrk/arch35/csyrk_netlib_reference.h and is shared bit-identically with
// the operator's host-side special-value fallback, so both compute the Netlib
// `csyrk` semantics (task doc §3.2: golden generated by the cblas Netlib
// complex implementation).
#include "cblas_threaded.h"
#include "csyrk_netlib_reference.h"

// The Netlib loop is O(n^2*k) single-threaded: on the arch22 CSV an n=k=8000
// golden costs minutes per case and pushed the full suite past the 30-minute
// PreSmoke timeout. Each column j only reads A and writes C(:,j), so the column
// range is partitioned across threads exactly like the other complex BLAS-3
// goldens (see cblas_threaded.h): per-column beta scaling and the l/i loop
// order stay untouched, keeping the result bit-identical to the serial call.
inline void CsyrkNetlibReference(
    aclblasFillMode_t uplo, aclblasOperation_t trans, int n, int k, const aclblasComplex* alpha,
    const aclblasComplex* A, int lda, const aclblasComplex* beta, aclblasComplex* C, int ldc)
{
    blas_test::ForEachChunk(n, [&](int j0, int len) {
        CsyrkNetlibReferenceCore(uplo, trans, n, k, alpha, A, lda, beta, C, ldc, j0, j0 + len);
    });
}
