/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef DOTEX_NPU_WRAPPER_H
#define DOTEX_NPU_WRAPPER_H

#include <cstdint>
#include <cstdlib>
#include <vector>

#include "acl/acl.h"
#include "cann_ops_blas.h"
#include "dotex_golden.h"
#include "dtype_utils.h"

// ── Pack float vector -> typed bytes for device transfer ──
inline std::vector<uint8_t> dotexPackVector(const float* src, int n, int inc, aclDataType dtype)
{
    if (src == nullptr || n <= 0) return {};

    int absInc = std::abs(inc);
    size_t totalEl = static_cast<size_t>(static_cast<int64_t>(n - 1) * absInc) + 1;
    size_t elemSz = dtypeByteSize(dtype);
    std::vector<uint8_t> dst(totalEl * elemSz, 0);

    for (int64_t i = 0; i < n; i++) {
        int64_t idx = (inc > 0) ? (i * inc) : ((n - 1 - i) * absInc);
        float v = src[idx];
        if (dtype == ACL_FLOAT16) {
            *reinterpret_cast<uint16_t*>(&dst[idx * elemSz]) = floatToFp16(v);
        } else if (dtype == ACL_BF16) {
            *reinterpret_cast<uint16_t*>(&dst[idx * elemSz]) = floatToBf16(v);
        } else {
            *reinterpret_cast<float*>(&dst[idx * elemSz]) = v;
        }
    }
    return dst;
}

// ── RAII helper for NPU device memory ──
struct DotexNpuMem {
    void* dX = nullptr;
    void* dY = nullptr;
    void* dResult = nullptr;
    ~DotexNpuMem() {
        if (dResult) aclrtFree(dResult);
        if (dY) aclrtFree(dY);
        if (dX) aclrtFree(dX);
    }
};

// ── Copy a packed typed vector to device ──
inline aclblasStatus_t dotexCopyToDevice(
    void*& dPtr, const std::vector<uint8_t>& packed, size_t bytes)
{
    if (packed.empty() || bytes == 0) return ACLBLAS_STATUS_SUCCESS;

    aclError aclRet = aclrtMalloc(&dPtr, bytes, ACL_MEM_MALLOC_HUGE_FIRST);
    if (aclRet != ACL_SUCCESS) return ACLBLAS_STATUS_ALLOC_FAILED;

    aclRet = aclrtMemcpy(dPtr, bytes, packed.data(), bytes, ACL_MEMCPY_HOST_TO_DEVICE);
    if (aclRet != ACL_SUCCESS) {
        aclrtFree(dPtr);
        dPtr = nullptr;
        return ACLBLAS_STATUS_INTERNAL_ERROR;
    }
    return ACLBLAS_STATUS_SUCCESS;
}

// ─────────────────────────────────────────────────────────────────────────────
// aclblasDotEx_npu — NPU wrapper
//
// Takes float* arrays (as generated by makeBlasStrided), packs them to the
// target dtype, transfers to device, calls aclblasDotEx, reads back result
// and converts back to float for comparison.
// ─────────────────────────────────────────────────────────────────────────────
inline aclblasStatus_t aclblasDotEx_npu(
    aclblasHandle_t handle, int n,
    const float* x, aclDataType xType, int incx,
    const float* y, aclDataType yType, int incy,
    float* result, aclDataType resultType, aclDataType executionType)
{
    if (handle == nullptr || n <= 0) {
        return aclblasDotEx(handle, n,
            static_cast<const void*>(x), xType, incx,
            static_cast<const void*>(y), yType, incy,
            static_cast<void*>(result), resultType, executionType);
    }

    DotexNpuMem mem;

    // Pack and copy x to device
    std::vector<uint8_t> packedX = dotexPackVector(x, n, incx, xType);
    size_t xBytes = packedX.size();
    aclblasStatus_t st = dotexCopyToDevice(mem.dX, packedX, xBytes);
    if (st != ACLBLAS_STATUS_SUCCESS) return st;

    // Pack and copy y to device
    std::vector<uint8_t> packedY = dotexPackVector(y, n, incy, yType);
    size_t yBytes = packedY.size();
    st = dotexCopyToDevice(mem.dY, packedY, yBytes);
    if (st != ACLBLAS_STATUS_SUCCESS) return st;

    // Allocate device result buffer
    size_t resultBytes = dtypeByteSize(resultType);
    aclError aclRet = aclrtMalloc(&mem.dResult, resultBytes, ACL_MEM_MALLOC_HUGE_FIRST);
    if (aclRet != ACL_SUCCESS) return ACLBLAS_STATUS_ALLOC_FAILED;

    // Launch kernel
    aclblasStatus_t ret = aclblasDotEx(
        handle, n,
        static_cast<const void*>(mem.dX), xType, incx,
        static_cast<const void*>(mem.dY), yType, incy,
        static_cast<void*>(mem.dResult), resultType, executionType);

    aclrtSynchronizeDevice();

    // Read back result
    if (ret == ACLBLAS_STATUS_SUCCESS && result != nullptr) {
        if (resultType == ACL_FLOAT) {
            aclrtMemcpy(result, sizeof(float), mem.dResult, sizeof(float), ACL_MEMCPY_DEVICE_TO_HOST);
        } else if (resultType == ACL_FLOAT16) {
            uint16_t halfResult = 0;
            aclrtMemcpy(&halfResult, sizeof(uint16_t), mem.dResult, sizeof(uint16_t), ACL_MEMCPY_DEVICE_TO_HOST);
            *result = fp16ToFloat(halfResult);
        } else if (resultType == ACL_BF16) {
            uint16_t bf16Result = 0;
            aclrtMemcpy(&bf16Result, sizeof(uint16_t), mem.dResult, sizeof(uint16_t), ACL_MEMCPY_DEVICE_TO_HOST);
            *result = bf16ToFloat(bf16Result);
        }
    }

    return ret;
}

#endif // DOTEX_NPU_WRAPPER_H
