/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#pragma once

#include <algorithm>
#include <cmath>
#include <cstddef>

#include "acl/acl.h"
#include "cann_ops_blas.h"

#ifdef CSYMM_ARCH35
// ===== arch35: 由参考 BLAS（Netlib csymm）计算 golden =====
#include <cblas.h>

#include "csymm_param.h"

/*!
 * \brief CPU golden for aclblasCsymm, generated by the reference BLAS (Netlib `csymm`).
 *
 * The golden is computed on exactly the same host buffers that are handed to the NPU
 * operator, so column-major layout, leading dimensions and the referenced triangle are
 * identical by construction: only the arithmetic differs.
 */
inline aclblasStatus_t CsymmCpuCheckParams(
    aclblasHandle_t handle, aclblasSideMode_t side, aclblasFillMode_t uplo, int m, int n,
    const aclblasComplex* alpha, const aclblasComplex* A, int lda, const aclblasComplex* B, int ldb,
    const aclblasComplex* beta, const aclblasComplex* C, int ldc)
{
    if (handle == nullptr) {
        return ACLBLAS_STATUS_HANDLE_IS_NULLPTR;
    }
    // Mirror the operator's validation order and status codes: an illegal
    // side/uplo is INVALID_ENUM (task book §2.4); only a negative dimension is
    // an INVALID_VALUE. Keeping the two classes separate here means the CSV
    // expectations can state the real contract instead of being patched up in
    // CsymmParam (see csymm_param.h).
    if (side != ACLBLAS_SIDE_LEFT && side != ACLBLAS_SIDE_RIGHT) {
        return ACLBLAS_STATUS_INVALID_ENUM;
    }
    if (uplo != ACLBLAS_UPPER && uplo != ACLBLAS_LOWER) {
        return ACLBLAS_STATUS_INVALID_ENUM;
    }
    if (m < 0 || n < 0) {
        return ACLBLAS_STATUS_INVALID_VALUE;
    }
    if (m == 0 || n == 0) {
        return ACLBLAS_STATUS_SUCCESS;
    }
    const int aDim = (side == ACLBLAS_SIDE_LEFT) ? m : n;
    if (alpha == nullptr || beta == nullptr || A == nullptr || B == nullptr || C == nullptr ||
        lda < std::max(1, aDim) || ldb < std::max(1, m) || ldc < std::max(1, m)) {
        return ACLBLAS_STATUS_INVALID_VALUE;
    }
    return ACLBLAS_STATUS_SUCCESS;
}

inline aclblasStatus_t aclblasCsymm_cpu(
    aclblasHandle_t handle, aclblasSideMode_t side, aclblasFillMode_t uplo, int m, int n,
    const aclblasComplex* alpha, const aclblasComplex* A, int lda, const aclblasComplex* B, int ldb,
    const aclblasComplex* beta, aclblasComplex* C, int ldc)
{
    const aclblasStatus_t st = CsymmCpuCheckParams(
        handle, side, uplo, m, n, alpha, A, lda, B, ldb, beta, C, ldc);
    if (st != ACLBLAS_STATUS_SUCCESS) {
        return st;
    }

    cblas_csymm(CblasColMajor,
        (side == ACLBLAS_SIDE_LEFT) ? CblasLeft : CblasRight,
        (uplo == ACLBLAS_UPPER) ? CblasUpper : CblasLower,
        m, n,
        static_cast<const void*>(alpha), static_cast<const void*>(A), lda,
        static_cast<const void*>(B), ldb,
        static_cast<const void*>(beta), static_cast<void*>(C), ldc);
    return ACLBLAS_STATUS_SUCCESS;
}

/*!
 * \brief Inf/NaN comparison used when the golden itself is non-finite.
 *
 * The mixed-tolerance strategy of test/frame/verify.h treats every non-finite element as a
 * failure, so rows whose inputs contain Inf/NaN cannot be checked with it. For those rows the
 * "non-finite pattern" is compared instead: an element matches when both values are NaN, both
 * are Inf with the same sign, or both are finite and bit-identical. The 0.99 matched-ratio
 * requirement of the precision standard still applies.
 */
inline bool CsymmVerifyNonFinitePattern(
    const float* output, const float* golden, size_t count, double requiredRatio, const std::string& caseId)
{
    size_t matched = 0;
    for (size_t i = 0; i < count; ++i) {
        const float outVal = output[i];
        const float goldVal = golden[i];
        const bool outNan = std::isnan(outVal);
        const bool goldNan = std::isnan(goldVal);
        const bool outInf = std::isinf(outVal);
        const bool goldInf = std::isinf(goldVal);
        bool ok;
        if (outNan || goldNan) {
            ok = (outNan && goldNan);
        } else if (outInf || goldInf) {
            ok = (outInf && goldInf) && (std::signbit(outVal) == std::signbit(goldVal));
        } else {
            ok = (outVal == goldVal);
        }
        if (ok) {
            ++matched;
        }
    }
    const double ratio = (count == 0) ? 1.0 : static_cast<double>(matched) / static_cast<double>(count);
    std::cout << "[" << caseId << "] non-finite pattern: matchedRatio=" << ratio
              << " (req=" << requiredRatio << "), " << (count - matched) << "/" << count << " mismatches"
              << std::endl;
    return ratio >= requiredRatio;
}
#else
// ===== arch22: 自带参考实现 + 多线程 cblas 封装 =====
#include "cblas_compat.h"
#include "cblas_threaded.h"

// Sentinel: all validations passed, proceed to compute.
static const int CSYMM_CPU_VALID_OK = 0x7FFFFFFF;

static bool CsymmIsValidSide(aclblasSideMode_t side) { return side == ACLBLAS_SIDE_LEFT || side == ACLBLAS_SIDE_RIGHT; }

static bool CsymmIsValidUplo(aclblasFillMode_t uplo) { return uplo == ACLBLAS_UPPER || uplo == ACLBLAS_LOWER; }

// Parameter validation aligned with the NPU implementation, including the order:
// enum legality and leading dimensions come before the m == 0 || n == 0 quick
// return, pointers after it.
static int ValidateCsymmCpuParams(
    aclblasHandle handle, aclblasSideMode_t side, aclblasFillMode_t uplo, int m, int n, int lda, int ldb, int ldc,
    const aclblasComplex* alpha, const aclblasComplex* beta, const aclblasComplex* A, const aclblasComplex* B,
    const aclblasComplex* C)
{
    if (handle == nullptr) {
        return static_cast<int>(ACLBLAS_STATUS_HANDLE_IS_NULLPTR);
    }
    if (!CsymmIsValidSide(side)) {
        return static_cast<int>(ACLBLAS_STATUS_INVALID_ENUM);
    }
    if (!CsymmIsValidUplo(uplo)) {
        return static_cast<int>(ACLBLAS_STATUS_INVALID_ENUM);
    }
    if (m < 0 || n < 0) {
        return static_cast<int>(ACLBLAS_STATUS_INVALID_VALUE);
    }
    // A is square of side m for side=LEFT and n for side=RIGHT.
    int ldaMin = (side == ACLBLAS_SIDE_LEFT) ? std::max(1, m) : std::max(1, n);
    if (lda < ldaMin) {
        return static_cast<int>(ACLBLAS_STATUS_INVALID_VALUE);
    }
    if (ldb < std::max(1, m) || ldc < std::max(1, m)) {
        return static_cast<int>(ACLBLAS_STATUS_INVALID_VALUE);
    }
    if (m == 0 || n == 0) {
        return static_cast<int>(ACLBLAS_STATUS_SUCCESS);
    }
    if (alpha == nullptr || beta == nullptr) {
        return static_cast<int>(ACLBLAS_STATUS_INVALID_VALUE);
    }
    if (A == nullptr || B == nullptr || C == nullptr) {
        return static_cast<int>(ACLBLAS_STATUS_INVALID_VALUE);
    }
    return CSYMM_CPU_VALID_OK;
}

// CPU golden for aclblasCsymm. Signature mirrors the NPU API exactly so the test
// harness can swap NPU/CPU calls one-for-one. Validation precedes the cblas call
// because CBLAS would crash on null pointers.
//
// Both alpha and beta are complex and passed by pointer, because CSYMM's output is
// a general matrix and nothing constrains the scalars. aclblasComplex = {float
// real; float imag} is binary-compatible with OpenBLAS's complex layout, so every
// cast below is a pure reinterpret.
inline aclblasStatus_t aclblasCsymm_cpu(
    aclblasHandle handle, aclblasSideMode_t side, aclblasFillMode_t uplo, int m, int n, const aclblasComplex* alpha,
    const aclblasComplex* A, int lda, const aclblasComplex* B, int ldb, const aclblasComplex* beta, aclblasComplex* C,
    int ldc)
{
    int st = ValidateCsymmCpuParams(handle, side, uplo, m, n, lda, ldb, ldc, alpha, beta, A, B, C);
    if (st != CSYMM_CPU_VALID_OK) {
        return static_cast<aclblasStatus_t>(st);
    }

    CBLAS_SIDE cblasSide = (side == ACLBLAS_SIDE_LEFT) ? CblasLeft : CblasRight;

    // CsymmThreaded splits the dense output along whichever extent leaves A whole
    // and drives one cblas_csymm per chunk from its own thread, which leaves every
    // element's accumulation order untouched. See cblas_threaded.h.
    blas_test::CsymmThreaded(
        cblasSide, ToCblasUplo(uplo), m, n, reinterpret_cast<const float*>(alpha),
        reinterpret_cast<const float*>(A), lda, reinterpret_cast<const float*>(B), ldb,
        reinterpret_cast<const float*>(beta), reinterpret_cast<float*>(C), ldc);

    return ACLBLAS_STATUS_SUCCESS;
}
#endif
